// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl3zG4RvsUQeLevoXC4Lw_6ozLaPuH_C0',
    appId: '1:565659495044:web:150e9bcc2f5b9c34c230d1',
    messagingSenderId: '565659495044',
    projectId: 'gr13-gamelink-fall-2025',
    authDomain: 'gr13-gamelink-fall-2025.firebaseapp.com',
    storageBucket: 'gr13-gamelink-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC95_jJ41a1B9t733ud2zkv2XgW4qDRtqk',
    appId: '1:565659495044:android:06f68196b96143f2c230d1',
    messagingSenderId: '565659495044',
    projectId: 'gr13-gamelink-fall-2025',
    storageBucket: 'gr13-gamelink-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutcdvOtVzqnVlll4LRIyl77-a6LoYeEg',
    appId: '1:565659495044:ios:7cbb143b2066532fc230d1',
    messagingSenderId: '565659495044',
    projectId: 'gr13-gamelink-fall-2025',
    storageBucket: 'gr13-gamelink-fall-2025.firebasestorage.app',
    iosBundleId: 'com.example.gameLinkGroup13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl3zG4RvsUQeLevoXC4Lw_6ozLaPuH_C0',
    appId: '1:565659495044:web:5caa276ce77ced0cc230d1',
    messagingSenderId: '565659495044',
    projectId: 'gr13-gamelink-fall-2025',
    authDomain: 'gr13-gamelink-fall-2025.firebaseapp.com',
    storageBucket: 'gr13-gamelink-fall-2025.firebasestorage.app',
  );
}
