// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYe-k7-t6JqeLqFEZw0wI2AkrAMjiHErA',
    appId: '1:525274573346:web:0a2fd4abf3c77d80cf387b',
    messagingSenderId: '525274573346',
    projectId: 'gr13-gamelink-fall25',
    authDomain: 'gr13-gamelink-fall25.firebaseapp.com',
    storageBucket: 'gr13-gamelink-fall25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH2ZGZoCAHlK6lzQZ9zr7oiOUKETERjLY',
    appId: '1:525274573346:android:37a4586935a162cbcf387b',
    messagingSenderId: '525274573346',
    projectId: 'gr13-gamelink-fall25',
    storageBucket: 'gr13-gamelink-fall25.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkV5zP0IFIP-_ezBKCyzzymGc6IMO5fU',
    appId: '1:525274573346:ios:2f672eb50d6f1f5bcf387b',
    messagingSenderId: '525274573346',
    projectId: 'gr13-gamelink-fall25',
    storageBucket: 'gr13-gamelink-fall25.firebasestorage.app',
    iosBundleId: 'com.example.gameLinkGroup13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYe-k7-t6JqeLqFEZw0wI2AkrAMjiHErA',
    appId: '1:525274573346:web:a984d48be7a365c9cf387b',
    messagingSenderId: '525274573346',
    projectId: 'gr13-gamelink-fall25',
    authDomain: 'gr13-gamelink-fall25.firebaseapp.com',
    storageBucket: 'gr13-gamelink-fall25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkV5zP0IFIP-_ezBKCyzzymGc6IMO5fU',
    appId: '1:525274573346:ios:2f672eb50d6f1f5bcf387b',
    messagingSenderId: '525274573346',
    projectId: 'gr13-gamelink-fall25',
    storageBucket: 'gr13-gamelink-fall25.firebasestorage.app',
    iosBundleId: 'com.example.gameLinkGroup13',
  );

}